In [1]:
import numpy as np

In [2]:
scalaire_1 = np.array(5)
scalaire_2 = np.array(6)
scalaire_1 + scalaire_2

np.int64(11)

In [3]:
scalaire_1 = np.array(5)
scalaire_2 = np.array(6)
resultat = scalaire_1 + scalaire_2
resultat

np.int64(11)

In [4]:
print(np.array(5) + np.array(6))

11


In [6]:
vecteur_1 = np.array([1, 2, 3])
vecteur_2 = np.array([3, 2, 1])
vecteur_3 = np.array([0, 1, -1])
resultat = vecteur_1 + vecteur_2 + vecteur_3
print(resultat)
print(resultat.shape)

[4 5 3]
(3,)


In [8]:
vecteur_1, vecteur_2, vecteur_3 = np.array([1, 2, 3]), np.array([3, 2, 1]), np.array([0, 1, -1])
print(vecteur_1+vecteur_2+vecteur_3)
print((vecteur_1+vecteur_2+vecteur_3).shape)

[4 5 3]
(3,)


In [9]:
resultat = np.array([1, 2, 3]) + np.array([3, 2, 1]) + np.array([0, 1, -1])
print(resultat)
print(resultat.shape)

[4 5 3]
(3,)


In [10]:
scalaire = np.array(0)
vecteur = np.array([125, 2185, 321, 665, 17, -8])
produit = scalaire * vecteur
print(produit)

[0 0 0 0 0 0]


In [11]:
m = np.array([[1, 2, 3], [4, 5, 6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
m1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
m2 = np.array([[8, 7], [6, 5], [4, 3], [2, 1]])
m1 + m2

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [4]:
import numpy as np

v1 = np.array([4, 7])
v2 = np.array([3, 6])

scalaire_a1 = np.array(2)
scalaire_a2 = np.array(3)
scalaire_a3 = np.array(1.5)

v1 = v1 * scalaire_a1
v2 = v2 * scalaire_a2

v3 = v1 + v2
resultat = v3 * scalaire_a3

print(resultat)


[25.5 48. ]
